/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package konsultasi;
import java.sql.Connection;
import konsultasi.registrasi;
import konsultasi.pengguna;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class jadwalkonsultasi extends javax.swing.JFrame {

    /**
     * Creates new form j
     */
    public jadwalkonsultasi() {
        initComponents();
        tabelJadwalKonsultasi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputtanggalkonsultasi = new javax.swing.JTextField();
        pilihnamadokter = new javax.swing.JComboBox<>();
        inputnamaibu = new javax.swing.JTextField();
        btnJadwalkan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelJadwalKonsultasi = new javax.swing.JTable();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Dokter");

        jLabel2.setFont(new java.awt.Font("Humnst777 BlkCn BT", 0, 18)); // NOI18N
        jLabel2.setText("Jadwal Konsultasi");

        jLabel3.setText("Nama");

        jLabel4.setText("Tanggal Konsultasi");

        inputtanggalkonsultasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputtanggalkonsultasiActionPerformed(evt);
            }
        });

        pilihnamadokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Lauren Sp.og", "Dr. Marchel Sp.og" }));
        pilihnamadokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihnamadokterActionPerformed(evt);
            }
        });

        inputnamaibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputnamaibuActionPerformed(evt);
            }
        });

        btnJadwalkan.setText("Jadwalkan Konsultasi");
        btnJadwalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalkanActionPerformed(evt);
            }
        });

        tabelJadwalKonsultasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dokter", "Tanggal Konsul"
            }
        ));
        jScrollPane1.setViewportView(tabelJadwalKonsultasi);

        btnback.setText("kembali");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputtanggalkonsultasi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputnamaibu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnJadwalkan, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnback))
                    .addComponent(pilihnamadokter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputnamaibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(pilihnamadokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputtanggalkonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJadwalkan)
                    .addComponent(btnback))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputnamaibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputnamaibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputnamaibuActionPerformed

    private void pilihnamadokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihnamadokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihnamadokterActionPerformed

    private void inputtanggalkonsultasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputtanggalkonsultasiActionPerformed
        String tanggal = inputtanggalkonsultasi.getText();
        try {
    java.sql.Date sqlDate = java.sql.Date.valueOf(tanggal);
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Format tanggal salah. Gunakan format YYYY-MM-DD.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}
    }//GEN-LAST:event_inputtanggalkonsultasiActionPerformed

    private void btnJadwalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalkanActionPerformed
    String nama = inputnamaibu.getText();
    String nama_dokter = pilihnamadokter.getSelectedItem().toString();
    String tanggal = inputtanggalkonsultasi.getText();

    // Validasi input
    if (nama.isEmpty() || tanggal.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Harap isi semua data!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Simpan ke database
    try (Connection conn = database_connection.getConnection()) {
        String query = "INSERT INTO konsultasi (nama_dokter, tanggal, nama) VALUES (?, ?, ?)";
        java.sql.PreparedStatement stmt = conn.prepareStatement(query);
        stmt.setString(1, nama_dokter);
        stmt.setString(2, tanggal);
        stmt.setString(3, nama);
        stmt.executeUpdate();

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelJadwalKonsultasi.getModel();
        model.addRow(new Object[]{nama_dokter, tanggal});

        // Reset form input
        inputnamaibu.setText("");
        inputtanggalkonsultasi.setText("");
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }    }//GEN-LAST:event_btnJadwalkanActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
this.dispose();

    // Membuka tampilan registrasi
    new dashboard().setVisible(true);    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jadwalkonsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jadwalkonsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jadwalkonsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jadwalkonsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jadwalkonsultasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJadwalkan;
    private javax.swing.JButton btnback;
    private javax.swing.JTextField inputnamaibu;
    private javax.swing.JTextField inputtanggalkonsultasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> pilihnamadokter;
    private javax.swing.JTable tabelJadwalKonsultasi;
    // End of variables declaration//GEN-END:variables

    private void tabelJadwalKonsultasi() {
    try (Connection conn = database_connection.getConnection()) {
        String query = "SELECT nama_dokter, tanggal_konsultasi FROM jadwal_konsultasi";
        java.sql.PreparedStatement stmt = conn.prepareStatement(query);
        var rs = stmt.executeQuery();

        // Bersihkan tabel
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelJadwalKonsultasi.getModel();
        model.setRowCount(0);

        // Tambahkan data ke tabel
        while (rs.next()) {
            String namaDokter = rs.getString("nama_dokter");
            String tanggalKonsultasi = rs.getString("tanggal_konsultasi");
            model.addRow(new Object[]{namaDokter, tanggalKonsultasi});
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}   
}
