package konsultasi;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;


/**
 *
 * @author MSI
 */
public class registrasi extends javax.swing.JFrame {

    /**
     * Creates new form registrasi
     */
    public registrasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputemail = new javax.swing.JTextField();
        inputnama = new javax.swing.JTextField();
        inputpassword = new javax.swing.JTextField();
        inputkonfirmasipassword = new javax.swing.JTextField();
        btnsignup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Humnst777 BlkCn BT", 0, 12)); // NOI18N
        jLabel1.setText("Registrasi");

        jLabel2.setText("Nama Lengkap");

        jLabel3.setText("Kata sandi");

        jLabel4.setText("Email");

        jLabel5.setText("Konfirmasi kata sandi");

        inputemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputemailActionPerformed(evt);
            }
        });

        inputnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputnamaActionPerformed(evt);
            }
        });

        inputpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputpasswordActionPerformed(evt);
            }
        });

        inputkonfirmasipassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputkonfirmasipasswordActionPerformed(evt);
            }
        });

        btnsignup.setText("Sign Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnsignup)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputnama, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputemail, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputkonfirmasipassword, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(inputemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(inputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputkonfirmasipassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnsignup)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputemailActionPerformed
String email = inputemail.getText();
    if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Format email tidak valid!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        inputemail.requestFocus();
    }    }//GEN-LAST:event_inputemailActionPerformed

    private void inputnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputnamaActionPerformed
      String nama = inputnama.getText();
    if (nama.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        inputnama.requestFocus();
    }
    }//GEN-LAST:event_inputnamaActionPerformed

    private void inputpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputpasswordActionPerformed
 String kata_sandi = inputpassword.getText();
    if (kata_sandi.length() < 8) {
        javax.swing.JOptionPane.showMessageDialog(this, "Password harus minimal 8 karakter!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        inputpassword.requestFocus();
    }    }//GEN-LAST:event_inputpasswordActionPerformed

    private void inputkonfirmasipasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputkonfirmasipasswordActionPerformed
 String password = inputpassword.getText();
    String konfirmasiPassword = inputkonfirmasipassword.getText();
    if (!konfirmasiPassword.equals(password)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Konfirmasi password tidak sesuai!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        inputkonfirmasipassword.requestFocus();
    }    }//GEN-LAST:event_inputkonfirmasipasswordActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
          System.out.println("Tombol Sign Up diklik!");

        String email = inputemail.getText();
    String nama = inputnama.getText();
    String kata_sandi = inputpassword.getText();
    String konfirmasiPassword = inputkonfirmasipassword.getText();

    // Validasi Email
    if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Format email tidak valid!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        inputemail.requestFocus();
        return;
    }

    // Validasi Nama
    if (nama.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        inputnama.requestFocus();
        return;
    }

    // Validasi Password
    if (kata_sandi.length() < 8) {
        javax.swing.JOptionPane.showMessageDialog(this, "Password harus minimal 8 karakter!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        inputpassword.requestFocus();
        return;
    }

    // Validasi Konfirmasi Password
    if (!konfirmasiPassword.equals(kata_sandi)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Konfirmasi password tidak sesuai!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        inputkonfirmasipassword.requestFocus();
        return;
    }

     // Simpan Data ke Database
    try {
        // Koneksi ke database
        Connection conn = database_connection.getConnection(); // Pastikan mengimpor DatabaseConnection
        if (conn != null) {
            String query = "INSERT INTO pengguna (nama, email, kata_sandi) VALUES (?, ?, ?)";
            try (java.sql.PreparedStatement stmt = conn.prepareStatement(query)) {
                stmt.setString(1, nama);
                stmt.setString(2, email);
                stmt.setString(3, kata_sandi);

                // Eksekusi query
                int rowsAffected = stmt.executeUpdate();
                if (rowsAffected > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Registrasi berhasil!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // Menampilkan Dashboard setelah registrasi berhasil
                    new dashboard().setVisible(true);

                    // Menutup frame registrasi
                    this.dispose(); // Menutup frame registrasi agar hanya tampilan dashboard yang terlihat
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Koneksi ke database gagal.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    // Menutup frame registrasi
    this.dispose(); // Menutup frame registrasi agar hanya tampilan dashboard yang terlihat
    inputemail.setText("");
    inputnama.setText("");
    inputpassword.setText("");
    inputkonfirmasipassword.setText("");

    }//GEN-LAST:event_btnsignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsignup;
    private javax.swing.JTextField inputemail;
    private javax.swing.JTextField inputkonfirmasipassword;
    private javax.swing.JTextField inputnama;
    private javax.swing.JTextField inputpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
